package Gestion;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Gestion.*;

/**
 *
 * @author Ivan
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private final UsaVehiculo gestor;
    private Vehiculo vehiculoActual;
    
    public VentanaPrincipal(){
        initComponents();
        gestor = new UsaVehiculo();
        this.setTitle("Sistema de gestion de taller mecanico");
        this.setLocationRelativeTo(null);
        
        rbConConvenio.setSelected(true); // Seleccionar uno por defecto
        txtAseguradora.setEnabled(false);
        
        
        pnlDatosReparacion.setVisible(false);
    }
    

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtPlacaBusqueda = new javax.swing.JTextField();
        btnBuscarPlaca = new javax.swing.JButton();
        lblEstadoVehiculo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDatosReparacion = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPlacaReparacion = new javax.swing.JTextField();
        btnBuscarParareparar = new javax.swing.JButton();
        lblVehiculoEncontrado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtDescripcionRep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCostoRep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbEstadoRep = new javax.swing.JComboBox<>();
        btnAgregarReparacion = new javax.swing.JButton();
        lblMensajeReparacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPlacaNueva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreProp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCelularProp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaProp = new javax.swing.JTextField();
        rbConConvenio = new javax.swing.JRadioButton();
        rbSinConvenio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtFechaAfiliacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAseguradora = new javax.swing.JTextField();
        btnRegistrarNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la placa:");

        txtPlacaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaBusquedaActionPerformed(evt);
            }
        });

        btnBuscarPlaca.setText("Buscar Placa");
        btnBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlacaActionPerformed(evt);
            }
        });

        jLabel10.setText("Busqueda placa:");

        btnBuscarParareparar.setText("Buscar");
        btnBuscarParareparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPararepararActionPerformed(evt);
            }
        });

        lblVehiculoEncontrado.setText(".");

        jLabel11.setText("Descripcion:");

        txtDescripcionRep.setText("jTextField1");

        jLabel12.setText("Costo: ");

        txtCostoRep.setText("jTextField1");
        txtCostoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoRepActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado Reparacion: ");

        cmbEstadoRep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagnostico", "Reparacion", "Verificada" }));
        cmbEstadoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoRepActionPerformed(evt);
            }
        });

        btnAgregarReparacion.setText("Agregar");
        btnAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarReparacionActionPerformed(evt);
            }
        });

        lblMensajeReparacion.setText("jLabel14");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcionRep, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(cmbEstadoRep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lblMensajeReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcionRep, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCostoRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbEstadoRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(btnAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lblMensajeReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout pnlDatosReparacionLayout = new javax.swing.GroupLayout(pnlDatosReparacion);
        pnlDatosReparacion.setLayout(pnlDatosReparacionLayout);
        pnlDatosReparacionLayout.setHorizontalGroup(
            pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                .addGroup(pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarParareparar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVehiculoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlDatosReparacionLayout.setVerticalGroup(
            pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPlacaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarParareparar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehiculoEncontrado))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", pnlDatosReparacion);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        jLabel3.setText("Placa vehiculo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel2.setText("Modelo vehiculo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jPanel1.add(lblPlacaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        jLabel4.setText("Datos Propietario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        txtNombreProp.setText("jTextField1");
        jPanel1.add(txtNombreProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 110, -1));

        jLabel7.setText("N. Celular:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        txtCelularProp.setText("jTextField1");
        jPanel1.add(txtCelularProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 110, -1));

        jLabel8.setText("Cedula: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        txtCedulaProp.setText("jTextField1");
        jPanel1.add(txtCedulaProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, -1));

        buttonGroup1.add(rbConConvenio);
        rbConConvenio.setText("Tiene convenio");
        jPanel1.add(rbConConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        buttonGroup1.add(rbSinConvenio);
        rbSinConvenio.setText("No tiene convenio");
        jPanel1.add(rbSinConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel9.setText("Fecha afiliacion: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
        jPanel1.add(txtFechaAfiliacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 120, 20));

        jLabel6.setText("Aseguradora:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        jPanel1.add(txtAseguradora, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 120, 20));

        btnRegistrarNuevo.setText("Registrar Vehiculo");
        jPanel1.add(btnRegistrarNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 170, 50));

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlacaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPlacaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstadoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaBusquedaActionPerformed

    private void btnBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlacaActionPerformed
        String placa = txtPlacaBusqueda.getText().trim();
    lblEstadoVehiculo.setText("");

    if (placa.isEmpty()) {
        lblEstadoVehiculo.setText("<html><font color='red'>ERROR: Ingrese la placa.</font></html>");
        // Ocultar componentes de registro si están visibles
        // if (pnlRegistroDatos != null) pnlRegistroDatos.setVisible(false); 
        return;
    }

    // Usar el método público de tu gestor
    Vehiculo veh = gestor.buscarPorPlaca(placa); 
    
    if (veh != null) {
        // Vehículo ENCONTRADO
        lblEstadoVehiculo.setText("<html><font color='green'>Vehículo con placa " + placa + " ENCONTRADO. Vaya a Pestaña 2.</font></html>");
        // Ocultar formulario de registro
        // if (pnlRegistroDatos != null) pnlRegistroDatos.setVisible(false); 
    } else {
        // Vehículo NO ENCONTRADO -> Mostrar REGISTRO
        lblEstadoVehiculo.setText("<html><font color='blue'>Vehículo " + placa + " NO registrado. Complete para ingresarlo.</font></html>");
        
        // Asignar la placa al campo de registro (si lo tienes, si no, lo usaremos de txtPlacaBusqueda)
        // Ejemplo: txtPlacaRegistro.setText(placa); 
        
        // Mostrar formulario de registro
}    // if (pnlRegistroDatos != null) pnlRegistroDatos.setVisible(true);
    }//GEN-LAST:event_btnBuscarPlacaActionPerformed

    private void txtCostoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoRepActionPerformed

    private void cmbEstadoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoRepActionPerformed

    private void btnBuscarPararepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPararepararActionPerformed
        String placa = txtPlacaReparacion.getText().trim();
    lblVehiculoEncontrado.setText(""); 
    lblMensajeReparacion.setText("");
    pnlDatosReparacion.setVisible(false);
    vehiculoActual = null;
    
    if (placa.isEmpty()) {
        lblVehiculoEncontrado.setText("<html><font color='red'>Ingrese la placa.</font></html>");
        return;
    }

    // Usar el método público buscarPorPlaca de UsaVehiculo (¡Asegúrate de que es public!)
    Vehiculo veh = gestor.buscarPorPlaca(placa); 
    
    if (veh != null) {
        // Vehículo ENCONTRADO
        vehiculoActual = veh; // ¡Guardar el objeto!
        
        String tipo = (veh instanceof VehiculoConConvenio) ? "CON CONVENIO" : "SIN CONVENIO";
        
        lblVehiculoEncontrado.setText("<html><font color='green'>Vehículo ENCONTRADO: " + veh.getModelo() + " | Tipo: " + tipo + "</font></html>");
        pnlDatosReparacion.setVisible(true); // Mostrar el formulario
    } else {
        // Vehículo NO ENCONTRADO
        lblVehiculoEncontrado.setText("<html><font color='red'>ERROR: Vehículo con placa " + placa + " NO registrado.</font></html>");
    }
    }//GEN-LAST:event_btnBuscarPararepararActionPerformed

    private void btnAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReparacionActionPerformed
        lblMensajeReparacion.setText("");
    
    if (vehiculoActual == null) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: Primero busque un vehículo válido.</font></html>");
        return;
    }

    String descripcion = txtDescripcionRep.getText().trim();
    String costoStr = txtCostoRep.getText().trim();
    String estado = (String) cmbEstadoRep.getSelectedItem(); 
    
    if (descripcion.isEmpty() || costoStr.isEmpty()) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: Descripción y costo son obligatorios.</font></html>");
        return;
    }
    
    try {
        // 1. Validar y convertir Costo
        int costo = Integer.parseInt(costoStr);
        
        // 2. Crear la Reparación
        Reparacion nuevaRep = new Reparacion(descripcion, estado, costo);
        
        // 3. Agregar y obtener resultado (polimorfismo: aplica descuento si es Convenio)
        String resultado = vehiculoActual.adicionarReparacion(nuevaRep);
        
        // 4. Mostrar el resultado (costo a pagar y garantía)
        lblMensajeReparacion.setText("<html><font color='blue'>REPARACIÓN REGISTRADA:</font><br>" + resultado + "</html>");
        
        // Limpiar campos
        txtDescripcionRep.setText("");
        txtCostoRep.setText("");
        
    } catch (NumberFormatException e) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: El costo debe ser un número entero sin puntos ni comas.</font></html>");
    } catch (Exception e) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: " + e.getMessage() + "</font></html>");
    }
    }//GEN-LAST:event_btnAgregarReparacionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarReparacion;
    private javax.swing.JButton btnBuscarParareparar;
    private javax.swing.JButton btnBuscarPlaca;
    private javax.swing.JButton btnRegistrarNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbEstadoRep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEstadoVehiculo;
    private javax.swing.JLabel lblMensajeReparacion;
    private javax.swing.JTextField lblPlacaNueva;
    private javax.swing.JLabel lblVehiculoEncontrado;
    private javax.swing.JPanel pnlDatosReparacion;
    private javax.swing.JRadioButton rbConConvenio;
    private javax.swing.JRadioButton rbSinConvenio;
    private javax.swing.JTextField txtAseguradora;
    private javax.swing.JTextField txtCedulaProp;
    private javax.swing.JTextField txtCelularProp;
    private javax.swing.JTextField txtCostoRep;
    private javax.swing.JTextField txtDescripcionRep;
    private javax.swing.JTextField txtFechaAfiliacion;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreProp;
    private javax.swing.JTextField txtPlacaBusqueda;
    private javax.swing.JTextField txtPlacaReparacion;
    // End of variables declaration//GEN-END:variables

}
