package Gestion;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Gestion.*;
import java.awt.HeadlessException;

/**
 *
 * @author Ivan
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private final UsaVehiculo gestor;
    private Vehiculo vehiculoActual;
    
    public VentanaPrincipal(){
        initComponents();
        gestor = new UsaVehiculo();
        this.setTitle("Sistema de gestion de taller mecanico");
        this.setLocationRelativeTo(null);
        
        rbConConvenio.setSelected(true); // Seleccionar uno por defecto
        cmbAseguradora.setEnabled(false);
        txtFechaAfiliacion.setEnabled(true);
        
        pnlDatosReparacion.setVisible(false);
    }
    

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtPlacaBusqueda = new javax.swing.JTextField();
        btnBuscarPlaca = new javax.swing.JButton();
        lblEstadoVehiculo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDatosReparacion = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPlacaReparacion = new javax.swing.JTextField();
        btnBuscarParareparar = new javax.swing.JButton();
        lblVehiculoEncontrado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtDescripcionRep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCostoRep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbEstadoRep = new javax.swing.JComboBox<>();
        btnAgregarReparacion = new javax.swing.JButton();
        lblMensajeReparacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreProp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCelularProp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaProp = new javax.swing.JTextField();
        rbSinConvenio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtFechaAfiliacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarNuevo = new javax.swing.JButton();
        rbConConvenio = new javax.swing.JRadioButton();
        cmbAseguradora = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        btnGenerarReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReportes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la placa:");

        txtPlacaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaBusquedaActionPerformed(evt);
            }
        });

        btnBuscarPlaca.setText("Buscar Placa");
        btnBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlacaActionPerformed(evt);
            }
        });

        jLabel10.setText("Busqueda placa:");

        btnBuscarParareparar.setText("Buscar");
        btnBuscarParareparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPararepararActionPerformed(evt);
            }
        });

        lblVehiculoEncontrado.setText(".");

        jLabel11.setText("Descripcion:");

        jLabel12.setText("Costo: ");

        txtCostoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoRepActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado Reparacion: ");

        cmbEstadoRep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagnostico", "Reparacion", "Verificada" }));
        cmbEstadoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoRepActionPerformed(evt);
            }
        });

        btnAgregarReparacion.setText("Agregar");
        btnAgregarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarReparacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcionRep, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(cmbEstadoRep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblMensajeReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcionRep, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCostoRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbEstadoRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(btnAgregarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMensajeReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosReparacionLayout = new javax.swing.GroupLayout(pnlDatosReparacion);
        pnlDatosReparacion.setLayout(pnlDatosReparacionLayout);
        pnlDatosReparacionLayout.setHorizontalGroup(
            pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                .addGroup(pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarParareparar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVehiculoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlDatosReparacionLayout.setVerticalGroup(
            pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosReparacionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlDatosReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPlacaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarParareparar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehiculoEncontrado))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignar reparacion", pnlDatosReparacion);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 30));

        jLabel3.setText("Placa vehiculo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel2.setText("Modelo vehiculo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        jLabel4.setText("Datos Propietario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));
        jPanel1.add(txtNombreProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 110, -1));

        jLabel7.setText("N. Celular:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));
        jPanel1.add(txtCelularProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 110, -1));

        jLabel8.setText("Cedula: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));
        jPanel1.add(txtCedulaProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, -1));

        buttonGroup1.add(rbSinConvenio);
        rbSinConvenio.setText("No tiene convenio");
        rbSinConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSinConvenioActionPerformed(evt);
            }
        });
        jPanel1.add(rbSinConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel9.setText("Fecha afiliacion: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
        jPanel1.add(txtFechaAfiliacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 130, 30));

        jLabel6.setText("Aseguradora:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        btnRegistrarNuevo.setText("Registrar Vehiculo");
        btnRegistrarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 170, 50));

        buttonGroup1.add(rbConConvenio);
        rbConConvenio.setText("Tiene convenio");
        rbConConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbConConvenioActionPerformed(evt);
            }
        });
        jPanel1.add(rbConConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 201, 120, 30));

        cmbAseguradora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAPFRE", "SURA", "ALLIANZ", "SOLIDARIA", "LIBERTY" }));
        jPanel1.add(cmbAseguradora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 160, 30));

        jTabbedPane1.addTab("registro", jPanel1);

        cmbTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar Todos los Vehiculos", "Detalles de Reparacion por Placa", "Porcentaje de Reparacion Verificada" }));

        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        txtAreaReportes.setColumns(20);
        txtAreaReportes.setRows(5);
        jScrollPane1.setViewportView(txtAreaReportes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnGenerarReporte))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("reportes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPlacaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstadoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblEstadoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaBusquedaActionPerformed

    private void btnBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlacaActionPerformed
        String placa = txtPlacaBusqueda.getText().trim();
    lblEstadoVehiculo.setText("");

    if (placa.isEmpty()) {
        lblEstadoVehiculo.setText("<html><font color='red'>ERROR: Ingrese la placa.</font></html>");
        // Ocultar componentes de registro si están visibles
        // if (pnlRegistroDatos != null) pnlRegistroDatos.setVisible(false); 
        return;
    }

    // Usar el método público de tu gestor
    Vehiculo veh = gestor.buscarPorPlaca(placa); 
    
    if (veh != null) {
        // Vehículo ENCONTRADO
        lblEstadoVehiculo.setText("<html><font color='green'>Vehículo con placa " + placa + " ENCONTRADO. Vaya a Pestaña 2.</font></html>");
        // Ocultar formulario de registro
        // if (pnlRegistroDatos != null) pnlRegistroDatos.setVisible(false); 
    } else {
        // Vehículo NO ENCONTRADO -> Mostrar REGISTRO
        lblEstadoVehiculo.setText("<html><font color='blue'>Vehículo " + placa + " NO registrado. Complete para ingresarlo.</font></html>");
        
        // Asignar la placa al campo de registro (si lo tienes, si no, lo usaremos de txtPlacaBusqueda)
        // Ejemplo: txtPlacaRegistro.setText(placa); 
        
        // Mostrar formulario de registro
}    // if (pnlRegistroDatos != null) pnlRegistroDatos.setVisible(true);
    }//GEN-LAST:event_btnBuscarPlacaActionPerformed

    private void txtCostoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoRepActionPerformed

    private void cmbEstadoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoRepActionPerformed

    private void btnBuscarPararepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPararepararActionPerformed
        String placa = txtPlacaReparacion.getText().trim();
    lblVehiculoEncontrado.setText(""); 
    lblMensajeReparacion.setText("");
    pnlDatosReparacion.setVisible(false);
    vehiculoActual = null;
    
    if (placa.isEmpty()) {
        lblVehiculoEncontrado.setText("<html><font color='red'>Ingrese la placa.</font></html>");
        return;
    }

    // Usar el método público buscarPorPlaca de UsaVehiculo (¡Asegúrate de que es public!)
    Vehiculo veh = gestor.buscarPorPlaca(placa); 
    
    if (veh != null) {
        // Vehículo ENCONTRADO
        vehiculoActual = veh; // ¡Guardar el objeto!
        
        String tipo = (veh instanceof VehiculoConConvenio) ? "CON CONVENIO" : "SIN CONVENIO";
        
        lblVehiculoEncontrado.setText("<html><font color='green'>Vehículo ENCONTRADO: " + veh.getModelo() + " | Tipo: " + tipo + "</font></html>");
        pnlDatosReparacion.setVisible(true); // Mostrar el formulario
    } else {
        // Vehículo NO ENCONTRADO
        lblVehiculoEncontrado.setText("<html><font color='red'>ERROR: Vehículo con placa " + placa + " NO registrado.</font></html>");
    }
    }//GEN-LAST:event_btnBuscarPararepararActionPerformed

    private void btnAgregarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReparacionActionPerformed
        lblMensajeReparacion.setText("");
    
    if (vehiculoActual == null) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: Primero busque un vehículo válido.</font></html>");
        return;
    }

    String descripcion = txtDescripcionRep.getText().trim();
    String costoStr = txtCostoRep.getText().trim();
    String estado = (String) cmbEstadoRep.getSelectedItem(); 
    
    if (descripcion.isEmpty() || costoStr.isEmpty()) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: Descripción y costo son obligatorios.</font></html>");
        return;
    }
    
    try {
        // 1. Validar y convertir Costo
        int costo = Integer.parseInt(costoStr);
        
        // 2. Crear la Reparación
        Reparacion nuevaRep = new Reparacion(descripcion, estado, costo);
        
        // 3. Agregar y obtener resultado (polimorfismo: aplica descuento si es Convenio)
        String resultado = vehiculoActual.adicionarReparacion(nuevaRep);
        
        // 4. Mostrar el resultado (costo a pagar y garantía)
        lblMensajeReparacion.setText("<html><font color='blue'>REPARACIÓN REGISTRADA:</font><br>" + resultado + "</html>");
        
        // Limpiar campos
        txtDescripcionRep.setText("");
        txtCostoRep.setText("");
        
    } catch (NumberFormatException e) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: El costo debe ser un número entero sin puntos ni comas.</font></html>");
    } catch (Exception e) {
        lblMensajeReparacion.setText("<html><font color='red'>ERROR: " + e.getMessage() + "</font></html>");
    }
    }//GEN-LAST:event_btnAgregarReparacionActionPerformed

    // Métodos para la Pestaña 3

    private void listarTodosLosVehiculos() {
    // 1. Llama al gestor para obtener la lista completa como una cadena de texto.
    // Usamos gestor.getVehiculos() para pasar toda la lista al método listarVehiculos.
    String reporte = gestor.listarVehiculos(gestor.getVehiculos());
    
    // 2. Muestra ese texto en tu JTextArea (txtAreaReportes).
    txtAreaReportes.setText(reporte);
}

private void mostrarDetalleReparaciones(String placa) {
    Vehiculo veh = gestor.buscarPorPlaca(placa); // Usa el método existente en UsaVehiculo
    
    if (veh != null) {
        // El toString() de Vehiculo debe contener todos los detalles y reparaciones
        txtAreaReportes.setText("--- DETALLE DEL VEHÍCULO: " + placa + " ---\n\n" + veh.toString());
    } else {
        txtAreaReportes.setText("ERROR: Vehículo con placa " + placa + " no encontrado.");
    }
}

private void mostrarPorcentajeVerificadas() {
    java.util.ArrayList<Vehiculo> lista = gestor.getVehiculos();
    if (lista.isEmpty()) {
        txtAreaReportes.setText("No hay vehículos registrados.");
        return;
    }
    
    StringBuilder sb = new StringBuilder();
    sb.append("--- PORCENTAJE DE REPARACIONES VERIFICADAS POR VEHÍCULO ---\n\n");
    
    for (Vehiculo veh : lista) {
        double porcentaje = veh.calcularPorcentajeVerificados();
        sb.append(String.format("Placa: %s | Modelo: %s\n", veh.getPlaca(), veh.getModelo()));
        sb.append(String.format("  -> Porcentaje Verificado: %.2f%%\n\n", porcentaje));
    }
    txtAreaReportes.setText(sb.toString());
}
    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
     txtAreaReportes.setText(""); // Limpia el área antes de cada reporte
    
    // Obtiene la posición (índice) de la opción seleccionada.
    int tipoReporte = cmbTipoReporte.getSelectedIndex();
    
    switch (tipoReporte) {
        case 0: // Corresponde a "Listar Todos los Vehículos" (Índice 0)
            listarTodosLosVehiculos();
            break;
            
        case 1: // Corresponde a "Detalle de Reparaciones por Placa" (Índice 1)
            String placa = javax.swing.JOptionPane.showInputDialog("Ingrese la placa del vehículo:");
            if (placa != null && !placa.trim().isEmpty()) {
                mostrarDetalleReparaciones(placa.trim());
            }
            break;
            
        case 2: // Corresponde a "Porcentaje de Reparaciones Verificadas" (Índice 2)
            mostrarPorcentajeVerificadas();
            break;
            
        default:
            // Esto solo ocurriría si no hay ninguna opción seleccionada (-1)
            txtAreaReportes.setText("Seleccione una opción válida.");
            break;
    }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnRegistrarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoActionPerformed
    try {
        
        // =======================================================
        // 1. OBTENER Y CONVERTIR TODOS LOS DATOS
        // =======================================================
        
        // Datos del Propietario (protegidos por NumberFormatException)
        String nombreProp = txtNombreProp.getText().trim();
        int cedula = Integer.parseInt(txtCedulaProp.getText().trim());
        int celular = Integer.parseInt(txtCelularProp.getText().trim());
        
        // Datos del Vehículo
        String placa = txtPlaca.getText().trim();
        String modelo = txtModelo.getText().trim();
        
        // Validación básica de campos de texto
        if (placa.isEmpty() || modelo.isEmpty() || nombreProp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar los campos de Placa, Modelo y Nombre.", "Error de Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Detiene el proceso si faltan campos
        }
        
        // Crear el objeto Propietario
        Propietario propietario = new Propietario(nombreProp, cedula, celular);
        
        // Crear el objeto Vehiculo (Con o Sin Convenio)
        Vehiculo nuevoVehiculo = null;

        if (rbConConvenio.isSelected()) {
            String fechaAfiliacionStr = txtFechaAfiliacion.getText().trim();
            // Asume que VehiculoConConvenio se crea con la fecha como String
            nuevoVehiculo = new VehiculoConConvenio(placa, modelo, propietario, fechaAfiliacionStr);
            
        } else { // rbSinConvenio.isSelected()
            String aseguradora = cmbAseguradora.getSelectedItem().toString();
        
        if (aseguradora.isEmpty() || aseguradora.equals("Seleccione Aseguradora")) { // Ajusta la validación si usas un ítem por defecto
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una Aseguradora.", "Error de Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        nuevoVehiculo = new VehiculoSinConvenio(placa, modelo, propietario, aseguradora);
    }

        // =======================================================
        // 2. ADICIONAR EL VEHÍCULO AL GESTOR (LA PARTE FALTANTE)
        // =======================================================
        boolean exito = gestor.adicionarVehiculo(nuevoVehiculo); 

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vehículo registrado con éxito.", "Registro OK", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // Opcional: limpiarCamposRegistro(); para resetear el formulario
        } else {
             // Esto puede ocurrir si el método adicionarVehiculo maneja duplicados
             javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo registrar el vehículo. (Posiblemente placa duplicada)", "Error de Guardado", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        
    } catch (NumberFormatException e) {
        // Captura si Cédula o Celular no son números válidos o están vacíos
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Cédula y Celular deben ser números enteros válidos y no pueden estar vacíos.", "Error de Datos Numéricos", javax.swing.JOptionPane.ERROR_MESSAGE);
        
    } catch (Exception e) {
        // Captura cualquier otro error, como un formato de fecha incorrecto
        javax.swing.JOptionPane.showMessageDialog(this, "Error grave durante el registro: " + e.getMessage(), "Error General", javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnRegistrarNuevoActionPerformed

    private void rbConConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbConConvenioActionPerformed
        txtFechaAfiliacion.setEnabled(true); 
    // Ahora deshabilita el JComboBox
    cmbAseguradora.setEnabled(false);
    }//GEN-LAST:event_rbConConvenioActionPerformed

    private void rbSinConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSinConvenioActionPerformed
       txtFechaAfiliacion.setEnabled(false);
    txtFechaAfiliacion.setText("");
    // Ahora habilita el JComboBox
    cmbAseguradora.setEnabled(true);
    }//GEN-LAST:event_rbSinConvenioActionPerformed
    
    private void limpiarCamposRegistro() {
    // Limpieza de campos de texto
    txtPlaca.setText("");
    txtModelo.setText("");
    txtNombreProp.setText("");
    txtCedulaProp.setText("");
    txtCelularProp.setText("");
    txtFechaAfiliacion.setText("");
    
    // --- CAMBIOS AQUÍ ---
    
    // 1. Limpia el JComboBox seleccionando el primer elemento (índice 0)
    cmbAseguradora.setSelectedIndex(0); 
    
    // 2. Establece el estado por defecto del formulario (rbSinConvenio)
    rbSinConvenio.setSelected(true);
    
    // Para que los campos se muestren y oculten correctamente al limpiar (Estado: SIN CONVENIO):
    // 3. Habilita el JComboBox de Aseguradora
    cmbAseguradora.setEnabled(true); 
    // 4. Deshabilita el campo de Fecha de Afiliación
    txtFechaAfiliacion.setEnabled(false); 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarReparacion;
    private javax.swing.JButton btnBuscarParareparar;
    private javax.swing.JButton btnBuscarPlaca;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegistrarNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbAseguradora;
    private javax.swing.JComboBox<String> cmbEstadoRep;
    private javax.swing.JComboBox<String> cmbTipoReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEstadoVehiculo;
    private javax.swing.JLabel lblMensajeReparacion;
    private javax.swing.JLabel lblVehiculoEncontrado;
    private javax.swing.JPanel pnlDatosReparacion;
    private javax.swing.JRadioButton rbConConvenio;
    private javax.swing.JRadioButton rbSinConvenio;
    private javax.swing.JTextArea txtAreaReportes;
    private javax.swing.JTextField txtCedulaProp;
    private javax.swing.JTextField txtCelularProp;
    private javax.swing.JTextField txtCostoRep;
    private javax.swing.JTextField txtDescripcionRep;
    private javax.swing.JTextField txtFechaAfiliacion;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreProp;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPlacaBusqueda;
    private javax.swing.JTextField txtPlacaReparacion;
    // End of variables declaration//GEN-END:variables

}
